### ISSUE TITLE
Suggest to add language support for Chinese(zh-CN)

### ISSUE THREAD

**Issue by soujyuhs16** [bumbummen99/SkyCraft#12]
Hello!I'm a Skycraft theme user from China.I love your theme very much.However, the theme does not have a Chinese language pack, which makes me feel a little inconvenient to use.Can you increase your support for Chinese?
Maybe you don't know Chinese, but it doesn't matter. Maybe I can help you translate the theme to Chinese and build the zh_CN.po.
Thankyou very much

**Comment by sdfonehs16** [comment]
I had reload zh_CN.po and zh_CN.mo which translated by myself in the fork"SkyCraft-Chinese-translation".

**Comment by sdfonehs16** [comment]
I had upload zh_CN.po and zh_CN.mo which translated by myself in the fork"SkyCraft-Chinese-translation".
Hope that you can add them to the Language folder.
